status = [
  "ci",
  "ci (x86_64-linux)",
  # "ci (x86_64-darwin)", Temporarily disabled due to space problems on MacOS runners
  "check-cabal-files",
  "build (9.2.5, windows-latest)"
]
timeout_sec = 10800
required_approvals = 1
block_labels = [ "WIP", "DO NOT MERGE" ]
delete_merged_branches = true
cut_body_after = "# Checklist"
